DELETE http://localhost:3003/api/blogs/68b80538e065576f5aeb9ba3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpa3UiLCJpZCI6IjY4YjgwNDZmNzJhODI4MjU0OGNlMGRlMCIsImlhdCI6MTc1Njg5ODIxOCwiZXhwIjoxNzU2OTAxODE4fQ.vccuDsjgtDEWKYRboVTxAc3HwUFEbYQw_XXf9oFPMRE